[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
